name: Gitleaks Scan

on:
  push:
    branches:
      - fix/security-avital
  pull_request:
    branches:
      - fix/security-avital

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --no-color --redact
